types:
    Company:
        label: "Company"

    Organization:
        label: "Organization"

    Person:
        label: "Person"

attributes:
    label:
        label: "Label"
        data_type: string

    type:
        label: "Type"
        data_type: type

    identifier:
        label: "Identifier"
        many: true
        data_type: string

    alias:
        label: "Alias"
        many: true
        data_type: string

    same_as:
        label: "Same as"
        data_type: entity
