types:
    Object:
        label: "Object"
        abstract: true

    Company:
        label: "Company"
        parent: Organization

    Organization:
        label: "Organization"
        parent: Object

    Person:
        label: "Person"
        parent: Object

attributes:
    label:
        label: "Label"
        data_type: string
        types:
            - 'Object'

    type:
        label: "Type"
        data_type: type
        types:
            - 'Object'

    identifier:
        label: "Identifier"
        many: true
        data_type: string
        types:
            - 'Object'

    alias:
        label: "Alias"
        many: true
        data_type: string
        types:
            - 'Object'

    same_as:
        label: "Same as"
        data_type: entity

    email:
        label: "E-Mail"
        data_type: string
        types:
            - 'Person'

    gender:
        label: "Gender"
        data_type: string
        types:
            - 'Person'

    birth_date:
        label: "Birth date"
        data_type: date
        types:
            - 'Person'

    death_date:
        label: "Death date"
        data_type: date
        types:
            - 'Person'
