types:
    Object:
        label: "Object"
        abstract: true
        attributes:
            label:
                label: "Label"
                data_type: string
            type:
                label: "Type"
                data_type: type
            identifier:
                label: "Identifier"
                many: true
                data_type: string
            links:
                label: "Links"
                many: true
                data_type: string
            same_as:
                label: "Same as"
                many: false
                data_type: entity

    Node:
        label: "Node"
        abstract: true
        parent: Object
        attributes:
            alias:
                label: "Alias"
                many: true
                data_type: string

    Link:
        label: "Link"
        abstract: true
        parent: Object
        attributes:
            start_date:
                label: "Start date"
                many: false
                data_type: date
            end_date:
                label: "End date"
                many: false
                data_type: date

    Actor:
        label: "Actor"
        abstract: true
        parent: Node
        attributes:
            posts_held:
                label: "Posts held"
                many: true
                data_type: entity

    Company:
        label: "Company"
        parent: Organization

    Organization:
        label: "Organization"
        parent: Actor
        attributes:
            has_posts:
                label: "Posts"
                many: true
                data_type: entity

    Person:
        label: "Person"
        parent: Actor
        attributes:
            email:
                label: "E-Mail"
                many: false
                data_type: string
            gender:
                label: "Gender"
                many: false
                data_type: string
            birth_date:
                label: "Birth date"
                many: false
                data_type: date
            death_date:
                label: "Death date"
                many: false
                data_type: date

    Post:
        label: "Post"
        parent: Link
        attributes:
            role:
                label: "Role"
                many: false
                data_type: string
            holder:
                label: "Post holder"
                many: false
                data_type: entity
            organization:
                    label: "Organization"
                    many: false
                    data_type: entity
